name: Rental API CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build
        run: mvn clean install -DskipTests

      - name: CheckStyle
        run: mvn checkstyle:checkstyle

      - name: Tests
        run: mvn surefire:test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./app/target/site/jacoco/jacoco.xml
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
